#include "editor/InterleavePrint.h"
#include "editor/KrlLineEdit.h"
#include "editor/MirrorObject.h"
#include "model/Transform.h"

#include <algorithm>
#include <cstdio>
#include <limits>
#include <map>

namespace {

// One object's paths for one layer, already in world space, ending at
// its last PRINT path -- the trailing/leading travels of the source
// layer are dropped, since the interleaved sequence generates its own
// safe-height transitions between segments instead.
struct LayerSegment {
    std::vector<Path> paths;
};

std::optional<LayerSegment> extractLayerSegment(const SceneObject& object, int layer) {
    LayerSegment segment;
    for (const auto& path : object.paths) {
        if (path.type != PathType::Print || path.layer != layer) continue;
        if (path.srcLine < 0 && path.cloneTemplateSrcLine < 0) continue; // no line to clone formatting from

        Path worldPath = path;
        worldPath.from = applyTransform(object.transform, path.from);
        worldPath.to = applyTransform(object.transform, path.to);
        segment.paths.push_back(worldPath);
    }
    if (segment.paths.empty()) return std::nullopt;
    return segment;
}

int highestLayer(const SceneObject& object) {
    int highest = 0;
    for (const auto& path : object.paths) {
        if (path.type == PathType::Print) highest = std::max(highest, path.layer);
    }
    return highest;
}

} // namespace

double highestWorldZ(const Scene& scene, const std::vector<int>& objectIds) {
    double highest = std::numeric_limits<double>::lowest();
    for (int id : objectIds) {
        for (const auto& object : scene.objects) {
            if (object.id != id) continue;
            for (const auto& path : object.paths) {
                highest = std::max(highest, applyTransform(object.transform, path.from).z);
                highest = std::max(highest, applyTransform(object.transform, path.to).z);
            }
        }
    }
    return highest == std::numeric_limits<double>::lowest() ? 0.0 : highest;
}

std::optional<SceneObject> buildInterleavedObject(const Scene& scene, const std::vector<int>& objectIdsInOrder,
                                                   const InterleaveOptions& options) {
    std::vector<const SceneObject*> objects;
    for (int id : objectIdsInOrder) {
        for (const auto& object : scene.objects) {
            if (object.id == id && highestLayer(object) > 0) objects.push_back(&object);
        }
    }
    if (objects.size() < 2) return std::nullopt;

    int maxLayer = 0;
    for (const auto* object : objects) maxLayer = std::max(maxLayer, highestLayer(*object));

    SceneObject merged;
    merged.name = objects.front()->name + " (interleaved x" + std::to_string(objects.size()) + ")";
    merged.sourceLines.push_back("DEF GCODEFORGE_INTERLEAVED()");
    merged.sourceLines.push_back("; Generated by GcodeForge: " + std::to_string(objects.size()) +
                                  " objects interleaved layer-by-layer for cooling.");
    merged.sourceLines.push_back("; The travel moves BETWEEN objects are meant to be cut apart after printing.");

    int nextPathNumber = 1;
    int currentLayerNumber = 0;
    std::optional<glm::dvec3> cursor; // where the nozzle currently is, world space

    // Appends one motion line + its Path. `templateLine` supplies the
    // format (motion command, E1-E6, C_VEL, comments) that
    // replaceKrlAxisValue then re-points at `to`; a generated travel
    // passes its own plain "LIN {...}" template instead.
    auto emit = [&](const glm::dvec3& from, const glm::dvec3& to, PathType type, int layer,
                     const std::string& templateLine, const std::string& motion, std::optional<double> speed) {
        std::string line = templateLine;
        line = replaceKrlAxisValue(line, 'X', to.x);
        line = replaceKrlAxisValue(line, 'Y', to.y);
        line = replaceKrlAxisValue(line, 'Z', to.z);

        Path path;
        path.number = nextPathNumber++;
        path.from = from;
        path.to = to;
        path.type = type;
        path.layer = layer;
        path.motion = motion;
        path.speed = speed;
        path.srcLine = static_cast<int>(merged.sourceLines.size());
        merged.sourceLines.push_back(line);
        merged.paths.push_back(path);
        cursor = to;
    };

    // Three-move safe transition: up to clearance height, across at that
    // height, then down to the next segment's first point. Splitting it
    // into three explicit moves (rather than one diagonal) is what
    // guarantees the crossing actually happens at safeTravelZMm the
    // whole way, instead of cutting a diagonal through a part.
    auto emitSafeTransition = [&](const glm::dvec3& target) {
        if (!cursor.has_value()) return;
        glm::dvec3 start = *cursor;
        double safeZ = std::max({options.safeTravelZMm, start.z, target.z});
        const std::string travelTemplate = "LIN {X 0,Y 0,Z 0} ; GCODEFORGE INTERLEAVE TRAVEL -- cut here after printing";

        emit(start, glm::dvec3(start.x, start.y, safeZ), PathType::Travel, -1, travelTemplate, "LIN", options.travelSpeed);
        emit(*cursor, glm::dvec3(target.x, target.y, safeZ), PathType::Travel, -1, travelTemplate, "LIN", options.travelSpeed);
        emit(*cursor, target, PathType::Travel, -1, travelTemplate, "LIN", options.travelSpeed);
    };

    // (source object index, source layer) -> merged layer number, so a
    // layer action attached to "object A, layer 3" can be re-attached to
    // whichever merged layer that segment actually became. Without this,
    // layer actions were silently dropped by interleaving -- meaning a
    // part-cooling command set up before mirroring would vanish, which is
    // exactly the kind of silent loss that already burned one real print.
    std::map<std::pair<size_t, int>, int> mergedLayerOf;

    for (int layer = 1; layer <= maxLayer; ++layer) {
        for (size_t objectIndex = 0; objectIndex < objects.size(); ++objectIndex) {
            const auto* object = objects[objectIndex];
            std::optional<LayerSegment> segment = extractLayerSegment(*object, layer);
            if (!segment.has_value()) continue; // this object has no such layer -- it just drops out of the rotation

            ++currentLayerNumber;
            mergedLayerOf[{objectIndex, layer}] = currentLayerNumber;
            const glm::dvec3& segmentStart = segment->paths.front().from;
            if (cursor.has_value()) {
                emitSafeTransition(segmentStart);
            }

            for (const auto& path : segment->paths) {
                int templateLineIndex = path.srcLine >= 0 ? path.srcLine : path.cloneTemplateSrcLine;
                const std::string& templateLine =
                    (templateLineIndex >= 0 && templateLineIndex < static_cast<int>(object->sourceLines.size()))
                        ? object->sourceLines[static_cast<size_t>(templateLineIndex)]
                        : std::string("LIN {X 0,Y 0,Z 0}");
                // A gap inside a source layer (its own internal travel
                // moves were dropped above) still needs the nozzle to
                // actually get there -- but within one object at one
                // layer that's a short in-layer reposition, not a
                // cross-object flight, so it doesn't need the full
                // safe-height treatment.
                if (cursor.has_value() && glm::length(path.from - *cursor) > 1e-4) {
                    emit(*cursor, path.from, PathType::Travel, -1,
                          "LIN {X 0,Y 0,Z 0} ; GCODEFORGE in-layer reposition", "LIN", options.travelSpeed);
                }
                emit(path.from, path.to, PathType::Print, currentLayerNumber, templateLine, path.motion, path.speed);
            }
        }
    }

    merged.sourceLines.push_back("END");
    if (merged.paths.empty()) return std::nullopt;

    // Re-attach every source object's layer actions to the merged layer
    // its segment became. Each object keeps its OWN actions -- if both a
    // part and its mirror have "cooling ON at layer 3", cooling fires
    // when each of them reaches its own layer 3, which is what per-layer
    // cooling means once the two are interleaved.
    for (size_t objectIndex = 0; objectIndex < objects.size(); ++objectIndex) {
        for (const auto& action : objects[objectIndex]->layerActions) {
            auto it = mergedLayerOf.find({objectIndex, action.layer});
            if (it == mergedLayerOf.end()) continue; // that layer never made it into the merge
            LayerAction remapped = action;
            remapped.layer = it->second;
            merged.layerActions.push_back(remapped);
        }
    }

    Layer layerInfo;
    // The merged object's layer table treats each emitted per-object
    // segment as its own layer (currentLayerNumber increments per
    // segment, not per physical Z) -- deliberate: for THIS object the
    // useful unit is "one continuous printed piece of one part," which
    // is exactly what the operator would want to select or speed-edit,
    // and it keeps the layer table readable rather than showing N
    // separate parts sharing one layer number.
    std::map<int, std::pair<int, int>> layerBounds;
    for (const auto& path : merged.paths) {
        if (path.type != PathType::Print) continue;
        auto it = layerBounds.find(path.layer);
        if (it == layerBounds.end()) {
            layerBounds[path.layer] = {path.number, path.number};
        } else {
            it->second.second = path.number;
        }
    }
    for (const auto& [layerNumber, bounds] : layerBounds) {
        layerInfo.layer = layerNumber;
        layerInfo.startPath = bounds.first;
        layerInfo.endPath = bounds.second;
        layerInfo.z = 0.0;
        for (const auto& path : merged.paths) {
            if (path.number == bounds.first) { layerInfo.z = path.to.z; break; }
        }
        merged.layers.push_back(layerInfo);
    }

    return merged;
}

std::optional<SceneObject> mirrorAndInterleave(Scene& scene, int sourceObjectId,
                                                const MirrorInterleaveOptions& options) {
    SceneObject* source = scene.findObject(sourceObjectId);
    if (!source || highestLayer(*source) <= 0) return std::nullopt;

    int copies = std::max(options.copies, 2);
    std::vector<int> ids{sourceObjectId};

    // Each copy mirrors the PREVIOUS one, so consecutive parts alternate
    // orientation and each is placed relative to the one before it --
    // that spreads them evenly in a row without separate placement logic.
    //
    // Re-look-up by id every iteration instead of holding a pointer:
    // Scene::addObject push_backs into a vector, which can reallocate and
    // invalidate any SceneObject* taken before the call.
    int previousId = sourceObjectId;
    for (int i = 1; i < copies; ++i) {
        SceneObject* previous = scene.findObject(previousId);
        if (!previous) break;
        SceneObject copy = mirrorObject(*previous, options.gapMm);
        int newId = scene.addObject(std::move(copy)).id;
        scene.toggleLink(previousId, newId);
        ids.push_back(newId);
        previousId = newId;
    }

    if (ids.size() < 2) return std::nullopt;

    InterleaveOptions interleave;
    interleave.safeTravelZMm = highestWorldZ(scene, ids) + options.travelClearanceMm;
    interleave.travelSpeed = options.travelSpeed;
    return buildInterleavedObject(scene, ids, interleave);
}
